#!/usr/bin/env bash
#A Bash script that loops from 1 to 10 and displays bad luck for the fourth iteration, good luck for the eighth iteration, and best school for the rest.

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	((count++))
done
